#ifndef __MISSING_H__
#include <missing.h>
#endif

#define ARCHITECTURE "arm"
#define HAVE_GCC_SYNC_ATOMICS
#define DISABLE_AOT
#define DISABLE_AOT_COMPILER
#define DISABLE_PORTABILITY 1
#define PLATFORM_NO_SYMLINKS 1
#define DISABLED_FEATURES "none"
#define DISABLE_ATTACH 1
#define DEFAULT_GC_NAME "SGen"
#define HAVE_CRYPT_RNG 1
#define HAVE_GETPROCESSID 1
#define HAVE_GC_ENABLE 1
#define HAVE_GC_H 1
#define HAVE_EPOLL 1
#define HAVE_INET_ATON 1
#define HAVE_INTTYPES_H 1
#define HAVE_ISINF 1
#define HAVE_MKSTEMP 1
#define HAVE_MOVING_COLLECTOR 1
#define HAVE_MSG_NOSIGNAL 1
#define HAVE_PTHREAD_ATTR_GETSTACK 1
#define HAVE_PTHREAD_ATTR_SETSTACKSIZE 1
#define HAVE_PTHREAD_H 1
#define HAVE_PTHREAD_MUTEX_TIMEDLOCK 1
#define HAVE_SGEN_GC 1
#define HAVE_SOL_IP 1
#define HAVE_SOL_TCP 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_STRUCT_IP_MREQ 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_TRUNC 1
#define HAVE_WCHAR_H 1
#define MONO_ZERO_LEN_ARRAY 1
#define NAME_DEV_RANDOM ""
#define PACKAGE "mono"
#define TARGET_ARM 1
#define ARM_FPU_VFP 1
#define NO_UNALIGNED_ACCESS	1 
#define SIZEOF_VOID_P 4
#define SIZEOF_REGISTER SIZEOF_VOID_P
#define STDC_HEADERS 1
#define USED_GC_NAME "SGen"
#define USE_INCLUDED_LIBGC 1
#define VERSION "2.11"
#define PLATFORM_NO_DRIVEINFO
#define VALGRIND_MAKE_MEM_DEFINED(a,b)
